source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'iRate', '~> 1.11'
pod 'OpenUDID', '~> 1.0.0'
pod 'TMCache', '~> 1.2.2'
pod 'SDWebImage', '~> 3.7.1'
pod 'SVProgressHUD', '~> 1.0'
pod 'EaseMobSDK', '~> 2.1.0'
pod 'MBProgressHUD', '~> 0.9'
pod 'MWPhotoBrowser', '~> 1.4.1'

