source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.2'
pod 'iRate', '~> 1.11'
pod 'OpenUDID', '~> 1.0.0'
pod 'SDWebImage', '~> 3.7.1'
pod "Qiniu", "~> 7.0"
pod 'TMCache', '~> 1.2'
pod 'UMengAnalytics-NO-IDFA'
pod 'MJRefresh'
